### ISSUE TITLE
Question about the dataset

### ISSUE THREAD

**Issue by XLechter** [thuml/Metasets#2]
Hi, thanks for your work.
I tried to test the performance of PointNet without generalization on your created dataset. However, I found PointNet cannot work when ModelNet-->ScanObjectNN with only 10% accuracy, and achieves about 40% accuracy when ShapeNet -->ScanObjectNN. I wonder if there any processing for ScanObjectNN dataset? I use almost the same setting in your PaddingData without density/drop/p_scan.
Thanks!

**Comment by XLechter** [comment]
Problem resovled after I check the point cloud alignment between modelnet11 and scanobjectnn11 and find there is a swapax operation for modelnet11.

**Comment by auniquesun** [comment]
@XLechter Can you share more experience on solving this problem? I encounter same problems as you stated, less than 10% accuracy on ModelNet -> ScanObjectNN.

**Comment by XLechter** [comment]
@auniquesun I remember this is solved by swapping the axis in Modelnet. You can check this:
![image](https://github.com/thuml/Metasets/assets/41005111/a20a64e6-6345-4181-bfeb-d916f4e879cd)
I remember  it works when I set the arg swapax to True for modelnet.
